package main.item;

@Deprecated
public enum ItemID {
    HEALTH_APPLE,
    HEALTH_APPLE_PURE,
    HEALTH_STEAK,
    HEALTH_CHOCOLATE,

    WEAPON_MACE,
    WEAPON_SWORD_SHORT,
    WEAPON_WAND,
    WEAPON_SWORD_SLIME,
    WEAPON_SPEAR_SLIME,

    RELIC_CURSE_HEAL,
    RELIC_CURSE_DETECTION,
    RELIC_ENEMY_INFORMATION,
    RELIC_FORESIGHT,
    RELIC_HOLDING,
    RELIC_REGENERATION,
    RELIC_RELICS,
    RELIC_SHIELDING,
    RELIC_SLIME,

    BUFF_DAMAGE,
    BUFF_HEALTH,
    BUFF_INVENTORY,
    BUFF_RELIC,
    BUFF_POISON,
}
